name: navinudge
description: A flutter App for Haptic Navigation

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.5.3
  flutter_blue_plus: ^1.32.11
  permission_handler: ^11.3.1
  get: ^4.6.6
  vector_math: ^2.1.4
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  flutter_polyline_points: ^2.1.0
  google_directions_api: ^0.10.0
  google_polyline_algorithm: ^3.1.0
  geofence_service: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/images/